/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package managment;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
//        Employee emp = new Employee();
//        Head dephead = new Head();
//        emp.setName("john");
////        dephead.createTask("work",emp);
//        assertEquals("john", emp.getName());
    }
}
